# Generated by Django 3.2.12 on 2023-03-08 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Destinatário',
                'verbose_name_plural': 'Destinatários',
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('titulo_email', models.CharField(max_length=200, verbose_name='Título do email')),
                ('legenda_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda do email')),
                ('titulo_alteracao_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título alteração do email')),
                ('corpo_email', django_quill.fields.QuillField(verbose_name='Corpo do email')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('enviar_usuario_criacao', models.BooleanField(verbose_name='Enviar usuário de criação')),
                ('destinatarios', models.ManyToManyField(blank=True, to='emails.Destinatario', verbose_name='Destinatários')),
            ],
            options={
                'verbose_name': 'Template do email',
                'verbose_name_plural': 'Templates dos emails',
            },
        ),
        migrations.CreateModel(
            name='MensagemEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagememail_requests_created', to=settings.AUTH_USER_MODEL)),
                ('template_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.templateemail', verbose_name='Template do email')),
            ],
            options={
                'verbose_name': 'Mensagem do email',
                'verbose_name_plural': 'Mensagens dos emails',
            },
        ),
    ]
