# Generated by Django 3.2.12 on 2023-03-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20230328_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagememail',
            name='codigo',
            field=models.CharField(max_length=50, null=True, verbose_name='Código'),
        ),
    ]
