# Generated by Django 3.2.12 on 2023-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_mensagememail_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagememail',
            name='corpo_email_text',
            field=models.CharField(max_length=200, null=True, verbose_name='Corpo do email em texto'),
        ),
    ]
