# Generated by Django 3.2.16 on 2024-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_configuracaoemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagememail',
            name='corpo_email_text',
            field=models.TextField(null=True, verbose_name='Corpo do email em texto'),
        ),
    ]
