# Generated by Django 3.2.9 on 2022-11-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('cod_cupom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo do Cupom')),
                ('validado_ate', models.DateField(auto_now=True, null=True, verbose_name='Validade até')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pagamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cóigo do pagamento')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('adicionais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamentos.adicional', verbose_name='Adicionais')),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamentos.cupom', verbose_name='Cupom')),
            ],
        ),
    ]
