# Generated by Django 3.2.9 on 2022-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='validado_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Validade até'),
        ),
    ]
