# Generated by Django 3.2.16 on 2023-01-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_cupom_validado_ate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='pagamento',
            field=models.CharField(choices=[('Pagar na mesa', 'Nome da opção'), ('Vale refeição', 'Nome da opção'), ('Vale-alimentação', 'Nome da opção'), ('Pagar com pix,', 'Nome da opção'), ('Cartão de crédito', 'Nome da opção'), ('Cartão de debito', 'Nome da opção')], default=1, max_length=50, verbose_name='Tipo pagamento'),
            preserve_default=False,
        ),
    ]
