# Generated by Django 3.2.16 on 2023-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_pagamento_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pagamento',
            field=models.CharField(choices=[('Pagar na mesa', 'Pagar na mesa'), ('Vale refeição', 'Vale refeição'), ('Vale-alimentação', 'Vale-alimentação'), ('Pagar com pix', 'Pagar com pix'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de debito', 'Cartão de debito')], default='Cartão de debito', max_length=50, verbose_name='Tipo pagamento'),
        ),
    ]
