# Generated by Django 3.2.16 on 2023-01-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_alter_pagamento_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='adicionais',
        ),
    ]
