# Generated by Django 3.2.16 on 2023-01-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_remove_pagamento_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='adicionais',
            field=models.ManyToManyField(blank=True, null=True, to='pagamentos.Adicional', verbose_name='Adicionais'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagamentos.cupom', verbose_name='Cupom'),
        ),
    ]
