# Generated by Django 3.2.16 on 2023-02-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_auto_20230131_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'verbose_name': 'Adicional', 'verbose_name_plural': 'Adicionais'},
        ),
        migrations.AlterModelOptions(
            name='cupom',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
