# Generated by Django 3.2.16 on 2023-02-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0007_auto_20230201_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='codigo_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Cóigo do pagamento'),
        ),
    ]
