# Generated by Django 3.2.16 on 2023-02-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0009_auto_20230201_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='validado_ate',
        ),
        migrations.AlterField(
            model_name='cupom',
            name='cod_cupom',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Codigo do Cupom'),
        ),
    ]
