# Generated by Django 3.2.16 on 2023-02-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0010_auto_20230201_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='validado_ate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validade até'),
        ),
    ]
