# Generated by Django 3.2.16 on 2023-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0011_cupom_validado_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='descricao',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
