# Generated by Django 3.2.16 on 2023-02-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0061_remove_pedidos_pagamento'),
        ('pagamentos', '0012_alter_cupom_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedidos', verbose_name='Pedido'),
        ),
    ]
