# Generated by Django 3.2.16 on 2023-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0013_pagamento_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='validado_ate',
            field=models.DateTimeField(null=True, verbose_name='Validade até'),
        ),
    ]
