# Generated by Django 3.2.16 on 2023-02-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0014_alter_cupom_validado_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='codigo_pagamento',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Cóigo do pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor do Desconto'),
        ),
    ]
