# Generated by Django 3.2.16 on 2023-02-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0015_auto_20230202_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='cupom',
        ),
    ]
