# Generated by Django 3.2.16 on 2023-02-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0017_remove_pagamento_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='desconto',
        ),
    ]
