# Generated by Django 3.2.16 on 2023-02-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0018_remove_pagamento_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor Pago'),
        ),
    ]
