# Generated by Django 3.2.16 on 2023-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0019_pagamento_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='codigo_pagamento',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Código do pagamento'),
        ),
    ]
