# Generated by Django 3.2.16 on 2023-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0020_alter_pagamento_codigo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='payment_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes do pagamento'),
        ),
    ]
