# Generated by Django 3.2.16 on 2023-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0021_pagamento_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='porcentagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='porcentagem'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
