# Generated by Django 3.2.16 on 2023-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0022_auto_20230612_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pagamento',
            field=models.CharField(choices=[('Pagamento na mesa', 'Pagamento na mesa'), ('card', 'Pagamento online')], default='Cartão de debito', max_length=50, verbose_name='Tipo pagamento'),
        ),
    ]
