# Generated by Django 3.2.16 on 2023-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0023_alter_pagamento_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pagamento',
            field=models.CharField(choices=[('Pagamento na mesa', 'Pagamento na mesa'), ('card', 'Pagamento online')], default='Pagamento na mesa', max_length=50, verbose_name='Tipo pagamento'),
        ),
    ]
