# Generated by Django 3.2.16 on 2023-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0025_alter_pagamento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='status_cupom',
            field=models.CharField(choices=[('Valido', 'Valido'), ('Utilizado', 'Utilizado'), ('Expirado', 'Expirado')], default='Valido', max_length=20),
        ),
    ]
