# Generated by Django 3.2.16 on 2023-09-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0170_alter_pedidos_taxa_de_atendimento'),
        ('pagamentos', '0026_cupom_status_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.restaurante', verbose_name='Restaurante'),
        ),
    ]
