# Generated by Django 3.2.16 on 2023-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0027_cupom_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='porcentagem',
        ),
        migrations.AlterField(
            model_name='cupom',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='porcentagem do cupom'),
        ),
    ]
