# Generated by Django 3.2.16 on 2023-09-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0028_auto_20230919_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='valor',
        ),
    ]
