# Generated by Django 3.2.16 on 2023-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0029_remove_cupom_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='porcentagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='porcentagem do cupom'),
        ),
    ]
