# Generated by Django 3.2.16 on 2023-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0030_cupom_porcentagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pagamento',
            field=models.CharField(choices=[('Pagamento na mesa', 'Pagamento na mesa'), ('Pagamento online', 'Pagamento online'), ('Pagamento pix', 'Pagamento pix')], default='Pagamento na mesa', max_length=50, verbose_name='Tipo pagamento'),
        ),
    ]
