# Generated by Django 3.2.16 on 2023-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0031_alter_pagamento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='valor_fixo',
            field=models.BooleanField(default=False, verbose_name='Ele é valor um valor Fixo? '),
        ),
    ]
