# Generated by Django 3.2.16 on 2023-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices_strip', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prices id do Strip')),
                ('quantidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='quantidade')),
                ('forma_pagamento', models.CharField(choices=[('Cartao Credito', 'Cartao Credito'), ('Cartao Debito', 'Cartao Debito'), ('Pix', 'Pix'), ('Pic Pay', 'Pic Pay')], default='Cartao Credito', max_length=30, verbose_name='Status do Pedido')),
                ('url_sucesso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Url sucesso')),
                ('url_cancelamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Url cancelamento')),
            ],
        ),
    ]
