# Generated by Django 3.2.16 on 2023-05-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apistripe', '0002_delete_apistripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produto', models.CharField(max_length=100, verbose_name='Nome')),
                ('strip_produto_id', models.CharField(max_length=100, verbose_name='Stripe Produto Id')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100, verbose_name='stripe_preço_id')),
                ('price', models.IntegerField(default=0, verbose_name='Preço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apistripe.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
            },
        ),
    ]
