# Generated by Django 3.2.16 on 2023-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistripe', '0003_price_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('token', models.CharField(max_length=100, verbose_name='Secret Key Stripe')),
            ],
            options={
                'verbose_name': 'configuração stripe',
                'verbose_name_plural': 'configurações Stripe',
            },
        ),
    ]
