# Generated by Django 3.2.16 on 2023-05-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apistripe', '0004_configstripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Produto',
        ),
    ]
