# Generated by Django 3.2.16 on 2023-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistripe', '0005_remove_produto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
