# Generated by Django 3.2.16 on 2023-05-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistripe', '0006_produto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Preço'),
        ),
    ]
