# Generated by Django 3.2.16 on 2023-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistripe', '0007_price_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook', models.TextField(verbose_name='webhook')),
            ],
            options={
                'verbose_name': 'Stripe',
                'verbose_name_plural': 'Stripes',
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
