# Generated by Django 3.2.16 on 2023-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistripe', '0008_auto_20230531_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe',
            name='request_data',
            field=models.TextField(default=1, verbose_name='webhook'),
            preserve_default=False,
        ),
    ]
