[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn stryn.wsgi:application --bind 0.0.0.0:${PORT}"
