[phases.setup]
nixPkgs = ["python312Full", "postgresql", "libffi", "pkg-config", "gcc"]

[phases.install]
cmds = [
  "export PKG_CONFIG_PATH=/nix/store/0qiyy7llb8ldillvlvjz1pyawhs5cvpk-libffi-3.4.6/lib/pkgconfig:$PKG_CONFIG_PATH",
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn stryn.wsgi:application --bind 0.0.0.0:${PORT} --workers=3 --timeout=180 --log-file -"
