[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",          # garante que pip exista
  "python -m pip install --upgrade pip",    # atualiza pip
  "python -m pip install -r requirements.txt"  # instala dependências
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn stryn.wsgi:application --bind 0.0.0.0:${PORT}"