[phases.setup]
nixPkgs = [
  "python312" # force rebuild
  "postgresql",  # Cliente Postgres
  "pkg-config",  # Necessário para dependências nativas
  "libpq"        # Bibliotecas do Postgres
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn stryn.wsgi:application --bind 0.0.0.0:${PORT} --workers=3 --timeout=180 --log-file -"
