[phases.setup]
nixPkgs = ["python312Full", "postgresql", "libffi", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn stryn.wsgi:application --workers=3 --timeout=180 --bind 0.0.0.0:${PORT} --log-file -"