[phases.setup]
nixPkgs = ["python312Full", "postgresql", "libffi", "libffi.dev", "pkg-config", "gcc"]

[phases.install]
cmds = [
  "export PKG_CONFIG_PATH=/nix/store/rhl22j48423aazmhjkwndpr1syzq5l46-libffi-3.4.6-dev/lib/pkgconfig:$PKG_CONFIG_PATH && ls -l /nix/store/rhl22j48423aazmhjkwndpr1syzq5l46-libffi-3.4.6-dev/lib/pkgconfig && pkg-config --modversion libffi && python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn stryn.wsgi:application --bind 0.0.0.0:${PORT} --workers=3 --timeout=180 --log-file -"