[phases.setup]
nixPkgs = [
  "python312Full",   # Python 3.12 completo com pip incluído
  "postgresql",      # Para pg_config
  "libffi",          # Para compilar cffi
  "gcc"              # Compilador C necessário para psycopg2 e cffi
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn stryn.wsgi:application --bind 0.0.0.0:${PORT} --workers=3 --timeout=180 --log-file -"