[phases.setup]
nixPkgs = [
  "python312Full",   # Python 3.12 completo
  "postgresql",      # Para compilar e acessar Postgres
  "libffi",          # Necessário para cffi e cryptography
  "pkg-config",      # Ajuda o pip a encontrar bibliotecas
  "gcc"              # Compilador para pacotes C
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",                    # Cria ambiente virtual
  ". /opt/venv/bin/activate",                    # Ativa ambiente virtual
  "python -m pip install --upgrade pip",         # Atualiza pip
  "python -m pip install -r requirements.txt"    # Instala dependências
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"     # Coleta arquivos estáticos
]

[start]
cmd = "gunicorn stryn.wsgi:application --bind 0.0.0.0:${PORT} --workers=3 --timeout=180 --log-file -"