# Generated by Django 3.2.16 on 2023-02-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Adiministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile', verbose_name='Adiministrador')),
            ],
            options={
                'verbose_name': 'Adiministrador',
                'verbose_name_plural': 'Adiministradores',
            },
        ),
    ]
