# Generated by Django 3.2.16 on 2023-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230201_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adiministrador',
        ),
    ]
