# Generated by Django 3.2.16 on 2023-02-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0083_auto_20230206_1119'),
        ('core', '0004_delete_adiministrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.restaurante'),
        ),
    ]
