# Generated by Django 3.2.9 on 2022-11-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempoEstimado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo Estimado')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='total_mesa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de Mesas'),
        ),
        migrations.CreateModel(
            name='ItensPedidoComplementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Produtos Adicionados')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor unitario do Produto')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor total dos Produtos Adicionados')),
                ('complemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.complementos', verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='IntensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Produto')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitario')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor total do Pedido')),
                ('complementos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.complementos', verbose_name='Complementos')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.item', verbose_name='Itens')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoComplementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome do Grupo de Complementos')),
                ('obrigatoriedade', models.BooleanField(default=False, verbose_name='Boleano')),
                ('quantidade', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Quantidade de Complemento')),
                ('complemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.complementos', verbose_name='Complementos')),
            ],
        ),
    ]
