# Generated by Django 3.2.9 on 2022-11-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20221116_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cliente')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('celular', models.CharField(blank=True, max_length=17, null=True, verbose_name='Numero Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField(blank=True, null=True, verbose_name='Número do Pedido')),
                ('data_criacao', models.DateField(auto_now=True, verbose_name='Data da Criação')),
                ('numero_mesa', models.IntegerField(blank=True, null=True, verbose_name='Númedo da Mesa')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal do Pedido')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total do Pedido')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.cliente', verbose_name='Cliente')),
                ('itens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.item', verbose_name='Itens')),
                ('tempo_estimado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.tempoestimado', verbose_name='Tempo Estimado')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='historico_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos.pedido'),
        ),
    ]
