# Generated by Django 3.2.9 on 2022-11-21 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20221118_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='categorias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardapio'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='itens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.item', verbose_name='Itens Para Cardapio'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='pedidos.restaurante', verbose_name='Nome do Restaurante'),
        ),
        migrations.AlterField(
            model_name='intenspedido',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.item', verbose_name='Itens'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardapio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='itens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.item', verbose_name='Itens'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tempo_estimado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.tempoestimado', verbose_name='Tempo Estimado'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo do Restaurante'),
        ),
    ]
