# Generated by Django 3.2.12 on 2022-12-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20221121_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição do Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='grupocomplementos',
            name='obrigatoriedade',
            field=models.BooleanField(default=False, verbose_name='Obrigatorio ?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_venda',
            field=models.BooleanField(default=False, verbose_name='Está Pausado ?'),
        ),
    ]
