# Generated by Django 3.2.12 on 2023-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20221207_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Nome do Item'),
        ),
    ]
