# Generated by Django 3.2.16 on 2023-01-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_cupom_validado_ate'),
        ('pedidos', '0008_item_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pagamentos.cupom', verbose_name='Cupom'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pagamentos.pagamento', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data da Criação'),
        ),
    ]
