# Generated by Django 3.2.16 on 2023-01-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20230124_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('Solicitado', 'solicitado'), ('Entregue', 'entregue'), ('Concluído', 'concluido'), ('Cancelado', 'cancelado')], default=1, max_length=20, verbose_name='Statu Pedido'),
            preserve_default=False,
        ),
    ]
