# Generated by Django 3.2.16 on 2023-01-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_status_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntensPedido',
            new_name='ItensPedido',
        ),
    ]
