# Generated by Django 3.2.16 on 2023-01-30 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_auto_20230130_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocomplementos',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Quantidade de Complemento'),
        ),
    ]
