# Generated by Django 3.2.16 on 2023-01-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_grupocomplementos_complemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedidocomplementos',
            name='complemento',
        ),
    ]
