# Generated by Django 3.2.16 on 2023-01-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pedidos', '0022_itenspedidocomplementos_complemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedido',
            name='item',
        ),
        migrations.AddField(
            model_name='cliente',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
