# Generated by Django 3.2.16 on 2023-01-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_auto_20230131_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.itemcardapio', verbose_name='Itens'),
        ),
    ]
