# Generated by Django 3.2.16 on 2023-01-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_itenspedido_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedido',
            name='complementos',
        ),
    ]
