# Generated by Django 3.2.16 on 2023-01-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0027_auto_20230131_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='tempo_estimado',
        ),
    ]
