# Generated by Django 3.2.16 on 2023-01-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0031_itemcardapio_grupo_complemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='itens',
        ),
    ]
