# Generated by Django 3.2.16 on 2023-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0032_auto_20230131_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.CategoriaCardapio', verbose_name='Categoria do Cardapio'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='itens',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.ItemCardapio', verbose_name='Itens Para Cardapio'),
        ),
    ]
