# Generated by Django 3.2.16 on 2023-01-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0033_auto_20230131_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcardapio',
            name='categoria',
        ),
    ]
