# Generated by Django 3.2.16 on 2023-01-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_alter_pagamento_pagamento'),
        ('pedidos', '0038_remove_pedidos_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pagamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagamentos.pagamento', verbose_name='Pagamento'),
        ),
    ]
