# Generated by Django 3.2.16 on 2023-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0041_remove_cliente_historico_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='historico_pedido',
            field=models.ManyToManyField(blank=True, null=True, related_name='historico', to='pedidos.Pedidos'),
        ),
    ]
