# Generated by Django 3.2.16 on 2023-02-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0042_cliente_historico_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='historico_pedido',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
