# Generated by Django 3.2.16 on 2023-02-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0045_pedidos_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('Solicitado', 'solicitado'), ('Entregue', 'entregue'), ('Concluído', 'concluido'), ('Cancelado', 'cancelado')], default='Solicitado', max_length=20, verbose_name='Statu Pedido'),
        ),
    ]
