# Generated by Django 3.2.16 on 2023-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0048_itenspedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero_pedido',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número do Pedido'),
        ),
    ]
