# Generated by Django 3.2.16 on 2023-02-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0049_alter_pedidos_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.itemcardapio', verbose_name='Itens'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='quantidade',
            field=models.IntegerField(null=True, verbose_name='Quantidade de Produto'),
        ),
    ]
