# Generated by Django 3.2.16 on 2023-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0055_alter_itenspedidocomplementos_valor_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='numero_pedido',
        ),
        migrations.AlterField(
            model_name='complementos',
            name='codigo_complemento',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Código do Complemento'),
        ),
        migrations.AlterField(
            model_name='complementos',
            name='nome',
            field=models.CharField(max_length=40, null=True, verbose_name='Nome do Complemento'),
        ),
    ]
