# Generated by Django 3.2.16 on 2023-02-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0059_alter_pedidos_status_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='total',
        ),
    ]
