# Generated by Django 3.2.16 on 2023-02-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0061_remove_pedidos_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='itenspedido',
            name='valor_unitario',
        ),
    ]
