# Generated by Django 3.2.16 on 2023-02-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0062_auto_20230201_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcardapio',
            name='codigo_item',
        ),
    ]
