# Generated by Django 3.2.16 on 2023-02-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0065_itemcardapio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome do Item'),
        ),
    ]
