# Generated by Django 3.2.16 on 2023-02-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0066_alter_itemcardapio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='tamanho_fome',
            field=models.CharField(choices=[('Nao se aplica', 'Nãoo se aplica'), ('1 pessoa', '1 pessoa'), ('2 pessoas', '2 pessoas'), ('3 pessoas', '3 pessoas'), ('4 pessoas', '4 pessoas')], max_length=50, verbose_name='Tamanho Fome'),
        ),
    ]
