# Generated by Django 3.2.16 on 2023-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0067_alter_itemcardapio_tamanho_fome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupocomplementos',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='grupocomplementos',
            name='complemento',
            field=models.ManyToManyField(null=True, to='pedidos.Complementos', verbose_name='Complementos'),
        ),
        migrations.AlterField(
            model_name='grupocomplementos',
            name='nome',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Nome do Grupo de Complementos'),
        ),
    ]
