# Generated by Django 3.2.16 on 2023-02-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0069_auto_20230202_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedidocomplementos',
            name='valor_unitario',
        ),
    ]
