# Generated by Django 3.2.16 on 2023-02-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0070_remove_itenspedidocomplementos_valor_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedidocomplementos',
            name='complemento',
        ),
    ]
