# Generated by Django 3.2.16 on 2023-02-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0072_auto_20230202_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedidocomplementos',
            name='item_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.itenspedido', verbose_name='Item do Pedido'),
        ),
    ]
