# Generated by Django 3.2.16 on 2023-02-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0077_auto_20230202_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='descricao',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descrição do Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Logo do Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nome',
            field=models.CharField(max_length=90, null=True, verbose_name='Nome do Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='total_mesa',
            field=models.IntegerField(null=True, verbose_name='Total de Mesas'),
        ),
    ]
