# Generated by Django 3.2.16 on 2023-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0079_remove_pedidos_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço do Produto'),
        ),
    ]
