# Generated by Django 3.2.16 on 2023-02-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0084_alter_itenspedido_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Criação'),
        ),
    ]
