# Generated by Django 3.2.16 on 2023-02-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0016_remove_pagamento_cupom'),
        ('pedidos', '0085_auto_20230206_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagamentos.cupom', verbose_name='Cupom'),
        ),
    ]
