# Generated by Django 3.2.16 on 2023-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0087_pedidos_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor do Desconto'),
        ),
    ]
