# Generated by Django 3.2.16 on 2023-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0089_itemcardapio_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacardapio',
            name='em_promocao',
            field=models.BooleanField(default=False, verbose_name='Está na Promoção?'),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='preco_promocao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço da Promoção'),
        ),
    ]
