# Generated by Django 3.2.16 on 2023-02-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0090_auto_20230213_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='desconto',
        ),
    ]
