# Generated by Django 3.2.16 on 2023-03-28 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0092_pedidos_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='usuario',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
    ]
