# Generated by Django 3.2.16 on 2023-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0094_restaurante_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='grupo_complemento',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.GrupoComplementos', verbose_name='Grupo de Complementos'),
        ),
    ]
