# Generated by Django 3.2.16 on 2023-04-12 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0095_alter_itemcardapio_grupo_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.CategoriaCardapio', verbose_name='Categorias do Cardapio'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardapio'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição do Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo do Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='total_mesa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de Mesas'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='usuario',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
    ]
