# Generated by Django 3.2.16 on 2023-04-13 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0100_alter_complementos_codigo_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementos',
            name='quantidade_maxima',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Quantidade Máxima'),
        ),
        migrations.AddField(
            model_name='complementos',
            name='quantidade_minima',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Quantidade Mínima'),
        ),
        migrations.AddField(
            model_name='grupocomplementos',
            name='opcao',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Multiplo', 'Multiplo')], max_length=100, null=True, verbose_name='Opção'),
        ),
    ]
