# Generated by Django 3.2.16 on 2023-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0101_auto_20230413_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedidocomplementos',
            name='item_pedido',
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='item_complemento',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.ItensPedidoComplementos', verbose_name='Itens de complementos pedido'),
        ),
    ]
