# Generated by Django 3.2.16 on 2023-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0104_auto_20230413_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacardapio',
            name='ordem',
            field=models.IntegerField(null=True, verbose_name='Ordem'),
        ),
    ]
