# Generated by Django 3.2.16 on 2023-04-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0106_alter_categoriacardapio_ordem'),
        ('pedidos', '0106_auto_20230428_1212'),
    ]

    operations = [
    ]
