# Generated by Django 3.2.16 on 2023-05-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0108_auto_20230428_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemCategoriaCardapio',
            fields=[
                ('ordem', models.IntegerField(blank=True, null=True, verbose_name='Ordem')),
                ('cardapio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.cardapio', verbose_name='Cardapio')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.categoriacardapio', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ordem categoria Cardapio',
                'verbose_name_plural': 'Ordem categorias cardapios',
            },
        ),
    ]
