# Generated by Django 3.2.16 on 2023-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0109_ordemcategoriacardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacardapio',
            name='em_promocao',
            field=models.BooleanField(default=False, verbose_name='Em promoção ?'),
        ),
    ]
