# Generated by Django 3.2.16 on 2023-05-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0110_categoriacardapio_em_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacardapio',
            name='ordem',
        ),
    ]
