# Generated by Django 3.2.16 on 2023-05-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0113_alter_categoriacardapio_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacardapio',
            name='ordem',
        ),
        migrations.DeleteModel(
            name='OrdemCategoriaCardapio',
        ),
    ]
