# Generated by Django 3.2.16 on 2023-05-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0117_restaurante_taxa_serviço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itenspedidocomplementos',
            name='item_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.itenspedido', verbose_name='Item do Pedido'),
        ),
    ]
