# Generated by Django 3.2.16 on 2023-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0118_auto_20230530_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('Sacola', 'Sacola'), ('Pago', 'Pago'), ('Pronto', 'Pronto'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Com erro', 'Com erro')], default='Sacola', max_length=20, verbose_name='Status do Pedido'),
        ),
    ]
