# Generated by Django 3.2.16 on 2023-05-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0119_merge_20230530_1241'),
        ('pedidos', '0119_pedidos_session_id'),
    ]

    operations = [
    ]
