# Generated by Django 3.2.16 on 2023-05-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0119_merge_20230531_0722'),
        ('pedidos', '0120_merge_20230530_1652'),
    ]

    operations = [
    ]
