# Generated by Django 3.2.16 on 2023-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0120_merge_20230531_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='checkou_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
