# Generated by Django 3.2.16 on 2023-05-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0120_merge_20230530_1652'),
        ('pedidos', '0121_pedidos_checkou_url'),
    ]

    operations = [
    ]
