# Generated by Django 3.2.16 on 2023-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0122_merge_20230531_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='checkou_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
