# Generated by Django 3.2.16 on 2023-05-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0124_merge_20230531_1313'),
        ('pedidos', '0124_merge_20230531_1645'),
    ]

    operations = [
    ]
