# Generated by Django 3.2.16 on 2023-06-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0125_merge_20230531_1345'),
        ('pedidos', '0125_merge_20230531_1705'),
    ]

    operations = [
    ]
