# Generated by Django 3.2.16 on 2023-06-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0124_merge_20230602_1421'),
        ('pedidos', '0125_merge_20230531_1705'),
    ]

    operations = [
    ]
