# Generated by Django 3.2.16 on 2023-06-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0124_merge_20230602_1421'),
        ('pedidos', '0126_merge_20230601_0716'),
    ]

    operations = [
    ]
