# Generated by Django 3.2.16 on 2023-06-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0126_merge_20230602_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='multiplicador_item_pedido',
            field=models.IntegerField(blank=True, default=1, max_length=5, null=True, verbose_name='Multiplicador Item Pedido'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço Item + Complementos'),
        ),
    ]
