# Generated by Django 3.2.16 on 2023-06-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0133_itenspedido_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='taxa_serviço',
        ),
    ]
