# Generated by Django 3.2.16 on 2023-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0134_remove_restaurante_taxa_serviço'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='taxa_servico',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Taxa de serviço'),
        ),
    ]
