# Generated by Django 3.2.16 on 2023-06-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0135_restaurante_taxa_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='tempo_estimado',
        ),
    ]
