# Generated by Django 3.2.16 on 2023-06-13 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0137_pedidos_tempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='tempo_estimado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.tempoestimado', verbose_name='Tempo Estimado'),
        ),
    ]
