# Generated by Django 3.2.16 on 2023-06-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0138_restaurante_tempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Cliente está aprovado para ver cardapio'),
        ),
    ]
