# Generated by Django 3.2.16 on 2023-06-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0139_cliente_aprovado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='aprovado',
        ),
    ]
