# Generated by Django 3.2.16 on 2023-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0140_remove_cliente_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Baner do Restaurante'),
        ),
    ]
