# Generated by Django 3.2.16 on 2023-07-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0143_restaurante_link_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='num_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Número da mesa é obrigatorio? '),
        ),
    ]
