# Generated by Django 3.2.16 on 2023-07-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0145_cliente_is_super'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_super',
        ),
    ]
