# Generated by Django 3.2.16 on 2023-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0146_remove_cliente_is_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='agencia',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='conta',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='digito',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='digito'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='inscricão estadual'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição municipal'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='numero',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CVC'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
    ]
