# Generated by Django 3.2.16 on 2023-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0149_restaurante_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numero'),
        ),
    ]
