# Generated by Django 3.2.16 on 2023-07-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0152_auto_20230714_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do cliente'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nome_cliente',
            field=models.CharField(default=1, max_length=200, verbose_name='Nome do cliente'),
            preserve_default=False,
        ),
    ]
