# Generated by Django 3.2.16 on 2023-07-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0153_auto_20230719_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='tempo_ideal',
            field=models.TimeField(blank=True, null=True, verbose_name='Tempo Bom'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tempo_limite',
            field=models.TimeField(blank=True, null=True, verbose_name='Tempo Limite'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tempo_medio',
            field=models.TimeField(blank=True, null=True, verbose_name='Tempo Médío'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do cliente'),
        ),
    ]
