# Generated by Django 3.2.16 on 2023-07-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0154_auto_20230720_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='chave_connect',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave Connect do Stripe'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='pedido_no_seu_restaurante',
            field=models.BooleanField(default=False, verbose_name='Pedido No meu Restaurante'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cliente'),
        ),
    ]
