# Generated by Django 3.2.16 on 2023-07-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0156_pedidos_chave_checkout_tranferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='chave_checkout_tranferencia',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='pocentagem_para_tranferencia',
            field=models.DecimalField(blank=True, decimal_places=2, default=90, max_digits=10, null=True, verbose_name='Valor em porcentagem que será enviado ao restaurante'),
        ),
    ]
