# Generated by Django 3.2.16 on 2023-08-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0163_pedidos_hora_status_aguardando_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='item_pronto',
            field=models.BooleanField(default=False, verbose_name='Item pronto'),
        ),
    ]
