# Generated by Django 3.2.9 on 2022-11-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome da Categoria')),
                ('status', models.BooleanField(default=False, verbose_name='Está Pausado ?')),
            ],
        ),
        migrations.CreateModel(
            name='Complementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome do Complemento')),
                ('codigo_complemento', models.CharField(blank=True, max_length=40, null=True, verbose_name='Código do Complemento')),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição do Complemento')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço do Complemento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('status_venda', models.BooleanField(default=False, verbose_name='Está Pausado ?')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=90, null=True, verbose_name='Nome do Restaurante')),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição do Restaurante')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo do Restaurante')),
                ('total_mesa', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Total de Mesas')),
                ('horario_abertura', models.TimeField(blank=True, null=True, verbose_name='Horario de Abertura')),
                ('horario_encerramento', models.TimeField(blank=True, null=True, verbose_name='Horario de Encerramento')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=60, verbose_name='Codigo Item')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço do Produto')),
                ('status_venda', models.BooleanField(default=False, verbose_name='Está Pauusado ?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardapio')),
                ('complemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.complementos', verbose_name='Complementos')),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Restaurante')),
                ('categorias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardapio')),
                ('itens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.item', verbose_name='Itens Para Cardapio')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.restaurante', verbose_name='Nome do Restaurante')),
            ],
        ),
    ]
