# Generated by Django 3.2.9 on 2022-11-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20221116_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='historico_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos.pedido'),
        ),
    ]
