# Generated by Django 3.2.9 on 2022-11-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_cliente_historico_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do cardapio'),
        ),
        migrations.AlterField(
            model_name='grupocomplementos',
            name='complemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.complementos', verbose_name='Complementos'),
        ),
        migrations.AlterField(
            model_name='grupocomplementos',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Complemento'),
        ),
        migrations.AlterField(
            model_name='intenspedido',
            name='complementos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.complementos', verbose_name='Complementos'),
        ),
        migrations.AlterField(
            model_name='item',
            name='complemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.complementos', verbose_name='Complementos'),
        ),
        migrations.AlterField(
            model_name='itenspedidocomplementos',
            name='complemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.complementos', verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.cliente', verbose_name='Cliente'),
        ),
    ]
