# Generated by Django 3.2.16 on 2023-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_rename_intenspedido_itenspedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemCardapio',
        ),
    ]
