# Generated by Django 3.2.16 on 2023-01-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_alter_pagamento_pagamento'),
        ('pedidos', '0012_rename_item_itemcardapio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
    ]
