# Generated by Django 3.2.16 on 2023-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_rename_pedido_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='tamanho_fome',
            field=models.CharField(choices=[('Nao se aplica', 'nao se aplica'), ('1 pessoa', 'uma pessoa'), ('2 pessoas', 'duas pessoas'), ('3 pessoas', 'tres pessoas'), ('4 pessoas', 'quatro pessoas')], default=1, max_length=50, verbose_name='Tamanho Fome'),
            preserve_default=False,
        ),
    ]
