# Generated by Django 3.2.16 on 2023-01-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_itemcardapio_tamanho_fome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcardapio',
            name='complemento',
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='grupo_complemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.grupocomplementos', verbose_name='Complementos'),
        ),
    ]
