# Generated by Django 3.2.16 on 2023-01-31 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_grupocomplementos_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedidocomplementos',
            name='total',
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardapio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='grupo_complemento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.grupocomplementos', verbose_name='Complementos'),
            preserve_default=False,
        ),
    ]
