# Generated by Django 3.2.16 on 2023-01-31 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_auto_20230131_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupocomplementos',
            name='complemento',
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='grupo_complemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.grupocomplementos', verbose_name='Complementos'),
        ),
    ]
