# Generated by Django 3.2.16 on 2023-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_auto_20230131_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocomplementos',
            name='complemento',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.Complementos', verbose_name='Complementos'),
        ),
    ]
