# Generated by Django 3.2.16 on 2023-01-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_remove_itenspedidocomplementos_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedidocomplementos',
            name='complemento',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.Complementos', verbose_name='Complemento'),
        ),
    ]
