# Generated by Django 3.2.16 on 2023-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_remove_itenspedido_complementos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='item_complemento',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.ItensPedidoComplementos', verbose_name='Itens de complementos pedido'),
        ),
    ]
