# Generated by Django 3.2.16 on 2023-01-31 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0026_itenspedido_item_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='itens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.itemcardapio', verbose_name='Itens'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='tempo_estimado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.tempoestimado', verbose_name='Tempo Estimado'),
        ),
    ]
