# Generated by Django 3.2.16 on 2023-01-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0028_remove_pedidos_tempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='tempo_estimado',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.TempoEstimado', verbose_name='Tempo Estimado'),
        ),
    ]
