# Generated by Django 3.2.16 on 2023-01-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0029_pedidos_tempo_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcardapio',
            name='grupo_complemento',
        ),
    ]
