# Generated by Django 3.2.16 on 2023-01-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0030_remove_itemcardapio_grupo_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='grupo_complemento',
            field=models.ManyToManyField(to='pedidos.GrupoComplementos', verbose_name='Complementos'),
        ),
    ]
