# Generated by Django 3.2.16 on 2023-01-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0035_itemcardapio_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pagamento',
        ),
    ]
