# Generated by Django 3.2.16 on 2023-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_alter_pagamento_pagamento'),
        ('pedidos', '0036_remove_pedidos_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pagamento',
            field=models.ManyToManyField(blank=True, null=True, to='pagamentos.Pagamento', verbose_name='Pagamento'),
        ),
    ]
