# Generated by Django 3.2.16 on 2023-02-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0039_pedidos_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardapio',
            options={'verbose_name': 'Cardapio', 'verbose_name_plural': 'Cardapios'},
        ),
        migrations.AlterModelOptions(
            name='categoriacardapio',
            options={'verbose_name': 'Categoria Cardapio', 'verbose_name_plural': 'Categorias Cardapios'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='complementos',
            options={'verbose_name': 'Complemento', 'verbose_name_plural': 'Complementos'},
        ),
        migrations.AlterModelOptions(
            name='grupocomplementos',
            options={'verbose_name': 'Grupo Complemento', 'verbose_name_plural': 'Grupos Complementos'},
        ),
        migrations.AlterModelOptions(
            name='itemcardapio',
            options={'verbose_name': 'Item cardapio', 'verbose_name_plural': 'Itens Cardapios'},
        ),
        migrations.AlterModelOptions(
            name='itenspedido',
            options={'verbose_name': 'Item Pedido', 'verbose_name_plural': 'Itens Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='itenspedidocomplementos',
            options={'verbose_name': 'Item Pedido Complemento', 'verbose_name_plural': 'Itens Pedidos Complementos'},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='tempoestimado',
            options={'verbose_name': 'Tempo Estimado', 'verbose_name_plural': 'Tempo Estimados'},
        ),
    ]
