# Generated by Django 3.2.16 on 2023-02-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0040_auto_20230201_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='historico_pedido',
        ),
    ]
