# Generated by Django 3.2.16 on 2023-02-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0043_auto_20230201_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='data_criacao',
        ),
    ]
