# Generated by Django 3.2.16 on 2023-02-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0044_remove_pedidos_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Criação'),
        ),
    ]
