# Generated by Django 3.2.16 on 2023-02-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0046_alter_pedidos_status_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='itens',
        ),
    ]
