# Generated by Django 3.2.16 on 2023-02-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0047_remove_pedidos_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedidos', verbose_name='Pedido'),
        ),
    ]
