# Generated by Django 3.2.16 on 2023-02-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0051_alter_itenspedido_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor total do Pedido'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário'),
        ),
    ]
