# Generated by Django 3.2.16 on 2023-02-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0052_auto_20230201_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedidocomplementos',
            name='quantidade',
            field=models.IntegerField(null=True, verbose_name='Quantidade de Produtos Adicionados'),
        ),
    ]
