# Generated by Django 3.2.16 on 2023-02-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0053_alter_itenspedidocomplementos_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedidocomplementos',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor unitario do Produto'),
        ),
    ]
