# Generated by Django 3.2.16 on 2023-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0056_auto_20230201_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='profile',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome do Cliente'),
        ),
    ]
