# Generated by Django 3.2.16 on 2023-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0058_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Entregue', 'Entregue'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=20, verbose_name='Status do Pedido'),
        ),
    ]
