# Generated by Django 3.2.16 on 2023-02-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0060_auto_20230201_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pagamento',
        ),
    ]
