# Generated by Django 3.2.16 on 2023-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0063_remove_itemcardapio_codigo_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcardapio',
            name='nome',
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Item'),
        ),
    ]
