# Generated by Django 3.2.16 on 2023-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0064_auto_20230201_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Item'),
        ),
    ]
