# Generated by Django 3.2.16 on 2023-02-02 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0068_auto_20230202_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocomplementos',
            name='quantidade_maxima',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Quantidade Máxima'),
        ),
        migrations.AddField(
            model_name='grupocomplementos',
            name='quantidade_minima',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Quantidade Mínima'),
        ),
    ]
