# Generated by Django 3.2.16 on 2023-02-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0071_remove_itenspedidocomplementos_complemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedido',
            name='item_complemento',
        ),
        migrations.AddField(
            model_name='itenspedidocomplementos',
            name='complemento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.complementos', verbose_name='Complemento'),
        ),
    ]
