# Generated by Django 3.2.16 on 2023-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0073_itenspedidocomplementos_item_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementos',
            name='foto',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='complementos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preço do Complemento'),
        ),
    ]
