# Generated by Django 3.2.16 on 2023-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0074_auto_20230202_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacardapio',
            name='nome',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='categoriacardapio',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Está pausado ?'),
        ),
    ]
