# Generated by Django 3.2.16 on 2023-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0075_auto_20230202_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='itens',
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='nome',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nome do cardapio'),
        ),
    ]
