# Generated by Django 3.2.16 on 2023-02-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0076_auto_20230202_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.CategoriaCardapio', verbose_name='Categorias do Cardapio'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.restaurante', verbose_name='Restaurante'),
        ),
    ]
