# Generated by Django 3.2.16 on 2023-02-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0078_auto_20230202_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='cupom',
        ),
    ]
