# Generated by Django 3.2.16 on 2023-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0080_alter_itemcardapio_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='grupo_complemento',
            field=models.ManyToManyField(to='pedidos.GrupoComplementos', verbose_name='Grupo de Complementos'),
        ),
    ]
