# Generated by Django 3.2.16 on 2023-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0081_alter_itemcardapio_grupo_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='categorias',
            field=models.ManyToManyField(null=True, to='pedidos.CategoriaCardapio', verbose_name='Categorias do Cardapio'),
        ),
    ]
