# Generated by Django 3.2.16 on 2023-02-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0082_alter_cardapio_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.restaurante'),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='tamanho_fome',
            field=models.CharField(choices=[('Nao se aplica', 'Não se aplica'), ('1 pessoa', '1 pessoa'), ('2 pessoas', '2 pessoas'), ('3 pessoas', '3 pessoas'), ('4 pessoas', '4 pessoas')], max_length=50, verbose_name='Tamanho Fome'),
        ),
    ]
