# Generated by Django 3.2.16 on 2023-02-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0083_auto_20230206_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.itemcardapio', verbose_name='Itens'),
        ),
    ]
