# Generated by Django 3.2.16 on 2023-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0017_remove_pagamento_adicionais'),
        ('pedidos', '0086_pedidos_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='adicionais',
            field=models.ManyToManyField(blank=True, null=True, to='pagamentos.Adicional', verbose_name='Adicionais'),
        ),
    ]
