# Generated by Django 3.2.16 on 2023-02-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0088_pedidos_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='opcao',
            field=models.BooleanField(default=True, verbose_name='Não, este item não tem complementos'),
        ),
    ]
