# Generated by Django 3.2.16 on 2023-03-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0093_restaurante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardapio'),
        ),
    ]
