# Generated by Django 3.2.16 on 2023-04-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0096_auto_20230412_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='grupo_complementos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.grupocomplementos', verbose_name='Grupo Complementos'),
        ),
    ]
