# Generated by Django 3.2.16 on 2023-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0097_cardapio_grupo_complementos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='grupo_complementos',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='grupo_complementos',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.GrupoComplementos', verbose_name='Grupo Complementos'),
        ),
    ]
