# Generated by Django 3.2.16 on 2023-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0098_auto_20230412_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocomplementos',
            name='complemento',
            field=models.ManyToManyField(blank=True, null=True, to='pedidos.Complementos', verbose_name='Complementos'),
        ),
    ]
