# Generated by Django 3.2.16 on 2023-04-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0099_alter_grupocomplementos_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementos',
            name='codigo_complemento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Código do Complemento'),
        ),
    ]
