# Generated by Django 3.2.16 on 2023-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0105_categoriacardapio_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacardapio',
            name='ordem',
            field=models.IntegerField(auto_created=True, null=True, unique=True, verbose_name='Ordem categoria'),
        ),
    ]
