# Generated by Django 3.2.16 on 2023-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0105_categoriacardapio_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacardapio',
            name='id',
        ),
        migrations.AlterField(
            model_name='categoriacardapio',
            name='ordem',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Ordem categoria'),
            preserve_default=False,
        ),
    ]
