# Generated by Django 3.2.16 on 2023-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0106_alter_categoriacardapio_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacardapio',
            name='ordem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordem'),
        ),
    ]
