# Generated by Django 3.2.16 on 2023-04-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0107_merge_20230428_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacardapio',
            name='em_promocao',
        ),
        migrations.AddField(
            model_name='categoriacardapio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriacardapio',
            name='ordem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordem'),
        ),
    ]
