# Generated by Django 3.2.16 on 2023-05-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0111_remove_categoriacardapio_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacardapio',
            name='ordem',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Ordem'),
        ),
    ]
