# Generated by Django 3.2.16 on 2023-05-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0116_alter_pedidos_status_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='taxa_serviço',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Taxa de serviço'),
        ),
    ]
