# Generated by Django 3.2.16 on 2023-05-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0117_restaurante_taxa_serviço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço Unitário'),
        ),
    ]
