# Generated by Django 3.2.16 on 2023-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0118_alter_itenspedido_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
