# Generated by Django 3.2.16 on 2023-05-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0118_alter_itenspedido_preco'),
        ('pedidos', '0118_auto_20230530_1239'),
    ]

    operations = [
    ]
