# Generated by Django 3.2.16 on 2023-05-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0121_merge_20230531_0840'),
        ('pedidos', '0121_pedidos_checkou_url'),
    ]

    operations = [
    ]
