# Generated by Django 3.2.16 on 2023-05-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0122_merge_20230531_0902'),
        ('pedidos', '0122_merge_20230531_0903'),
    ]

    operations = [
    ]
