# Generated by Django 3.2.16 on 2023-05-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0119_alter_pedidos_status_pedido'),
        ('pedidos', '0123_alter_pedidos_checkou_url'),
    ]

    operations = [
    ]
