# Generated by Django 3.2.16 on 2023-05-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0123_alter_pedidos_checkou_url'),
        ('pedidos', '0123_merge_20230531_0925'),
    ]

    operations = [
    ]
