# Generated by Django 3.2.16 on 2023-06-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0127_auto_20230602_1520'),
        ('pedidos', '0127_merge_20230602_1458'),
    ]

    operations = [
    ]
