# Generated by Django 3.2.16 on 2023-06-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0128_merge_20230602_1522'),
        ('pedidos', '0128_merge_20230602_1528'),
    ]

    operations = [
    ]
