# Generated by Django 3.2.16 on 2023-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0128_merge_20230602_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='preco',
            new_name='preco_item_mais_complementos',
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='valor_unitario_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitário Item'),
        ),
        migrations.AddField(
            model_name='itenspedidocomplementos',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='itenspedidocomplementos',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('Sacola', 'Sacola'), ('Pago', 'Pago'), ('Em preparo', 'Em preparo'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Com erro', 'Com erro')], default='Sacola', max_length=20, verbose_name='Status do Pedido'),
        ),
    ]
