# Generated by Django 3.2.16 on 2023-06-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0129_auto_20230605_1441'),
        ('pedidos', '0129_merge_20230605_0819'),
    ]

    operations = [
    ]
