# Generated by Django 3.2.16 on 2023-06-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0130_merge_20230606_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('Sacola', 'Sacola'), ('Aguardando Pagamento Mesa', 'Aguardando Pagamento Mesa'), ('Pago', 'Pago'), ('Aguardando Preparo', 'Aguardando Preparo'), ('Em preparo', 'Em preparo'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Com erro', 'Com erro')], default='Sacola', max_length=25, verbose_name='Status do Pedido'),
        ),
    ]
