# Generated by Django 3.2.16 on 2023-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0132_alter_pedidos_status_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='observacoes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações do item pedido'),
        ),
    ]
