# Generated by Django 3.2.16 on 2023-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0141_restaurante_baner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='checkou_url',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cliente_identificado',
            field=models.BooleanField(default=True, verbose_name='cliente cadastrado'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='hash_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hash_cliente'),
        ),
    ]
