# Generated by Django 3.2.16 on 2023-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0142_auto_20230706_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='link_restaurante',
            field=models.TextField(blank=True, null=True, verbose_name='Qr code Restaurante'),
        ),
    ]
