# Generated by Django 3.2.16 on 2023-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0144_restaurante_num_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_super',
            field=models.BooleanField(default=False, verbose_name='É super usuario?'),
        ),
    ]
