# Generated by Django 3.2.16 on 2023-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0148_remove_restaurante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RR', 'RR'), ('RO', 'RO'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='AC', max_length=2, verbose_name='UF'),
        ),
    ]
