# Generated by Django 3.2.16 on 2023-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0150_alter_restaurante_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CVC'),
        ),
    ]
