# Generated by Django 3.2.16 on 2023-07-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0151_restaurante_cvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='agencia',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner do Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.categoriacardapio', verbose_name='Categoria do Cardápio'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='digito',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='horario_abertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='horario_encerramento',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Encerramento'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscricão Estadual'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='link_restaurante',
            field=models.TextField(blank=True, null=True, verbose_name='QR code Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='num_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Número da mesa é obrigatório? '),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='taxa_servico',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Taxa de serviço em porcentagem'),
        ),
    ]
