# Generated by Django 3.2.16 on 2023-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0153_auto_20230719_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do cliente'),
        ),
    ]
