# Generated by Django 3.2.16 on 2023-07-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0154_alter_pedidos_nome_cliente'),
        ('pedidos', '0154_auto_20230720_0840'),
    ]

    operations = [
    ]
