# Generated by Django 3.2.16 on 2023-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0155_auto_20230724_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='chave_checkout_tranferencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
