# Generated by Django 3.2.16 on 2023-07-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0155_merge_20230721_0744'),
        ('pedidos', '0156_pedidos_chave_checkout_tranferencia'),
    ]

    operations = [
    ]
