# Generated by Django 3.2.16 on 2023-07-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0157_auto_20230727_1236'),
        ('pedidos', '0157_merge_20230727_1221'),
    ]

    operations = [
    ]
