# Generated by Django 3.2.16 on 2023-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0160_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='hash_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hash_cliente'),
        ),
    ]
