# Generated by Django 3.2.16 on 2023-08-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0158_merge_20230731_1215'),
        ('pedidos', '0160_alter_cliente_usuario'),
    ]

    operations = [
    ]
