# Generated by Django 3.2.16 on 2023-08-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0161_cliente_hash_cliente'),
        ('pedidos', '0161_merge_20230803_0932'),
    ]

    operations = [
    ]
