# Generated by Django 3.2.16 on 2023-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0161_cliente_hash_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='hora_status_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora que status mudou para pago'),
        ),
    ]
