# Generated by Django 3.2.16 on 2023-08-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0162_merge_20230816_1004'),
        ('pedidos', '0162_pedidos_hora_status_pago'),
    ]

    operations = [
    ]
