# Generated by Django 3.2.16 on 2023-08-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0162_pedidos_hora_status_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='hora_status_aguardando_preparo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora que status mudou para aguardando preparo'),
        ),
    ]
