# Generated by Django 3.2.16 on 2023-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0163_merge_20230822_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='hora_status_aguardando_preparo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora que status mudou para aguardando preparo'),
        ),
    ]
