# Generated by Django 3.2.16 on 2023-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0163_merge_20230822_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='item_pronto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Item pronto'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='hora_status_aguardando_preparo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora que status mudou para aguardando preparo'),
        ),
    ]
