# Generated by Django 3.2.16 on 2023-08-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0163_pedidos_hora_status_aguardando_preparo'),
        ('pedidos', '0164_pedidos_hora_status_aguardando_preparo'),
    ]

    operations = [
    ]
