# Generated by Django 3.2.16 on 2023-08-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0164_auto_20230823_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='hora_status_aguardando_preparo',
        ),
    ]
