# Generated by Django 3.2.16 on 2023-08-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0165_alter_pedidos_item_pronto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='item_pronto',
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='item_pronto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Item pronto'),
        ),
    ]
