# Generated by Django 3.2.16 on 2023-09-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0166_auto_20230823_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='pedido_no_seu_restaurante',
        ),
    ]
