# Generated by Django 3.2.16 on 2023-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0167_remove_restaurante_pedido_no_seu_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacardapio',
            name='nome',
            field=models.CharField(max_length=40, null=True, verbose_name='Nome da Categoria'),
        ),
    ]
