# Generated by Django 3.2.16 on 2023-09-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0168_alter_categoriacardapio_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='taxa_servico',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='taxa_de_atendimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de atendimento '),
        ),
    ]
