# Generated by Django 3.2.16 on 2023-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0169_auto_20230919_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='taxa_de_atendimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Taxa de atendimento '),
        ),
    ]
