# Generated by Django 3.2.16 on 2023-09-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0170_alter_pedidos_taxa_de_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='taxa_de_atendimento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Taxa de atendimento '),
        ),
    ]
