# Generated by Django 3.2.16 on 2023-09-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0171_alter_pedidos_taxa_de_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='taxa_de_atendimento',
        ),
    ]
