# Generated by Django 3.2.16 on 2023-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0173_pedidos_taxa_de_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='taxa_de_atendimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de atendimento '),
        ),
    ]
