# Generated by Django 3.2.16 on 2023-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0174_alter_pedidos_taxa_de_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
