# Generated by Django 3.2.16 on 2023-10-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0175_pedidos_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='tempo_estimado',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='chave_asaas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave Connect do Asaas'),
        ),
    ]
