# Generated by Django 3.2.16 on 2023-12-06 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0176_auto_20231011_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacardapio',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de criação'),
        ),
    ]
