# Generated by Django 3.2.16 on 2023-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0177_categoriacardapio_usuario_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('Sacola', 'Sacola'), ('Aguardando Pagamento Mesa', 'Aguardando Pagamento Mesa'), ('Aguardando Gestor Pedido', 'Aguardando Gestor Pedido'), ('Pago', 'Pago'), ('Aguardando Preparo', 'Aguardando Preparo'), ('Em preparo', 'Em preparo'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Com erro', 'Com erro'), ('Estornado', 'Estornado')], default='Sacola', max_length=25, verbose_name='Status do Pedido'),
        ),
    ]
