# Generated by Django 3.2.16 on 2023-12-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0178_alter_pedidos_status_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('Sacola', 'Sacola'), ('Aguardando Pagamento Mesa', 'Aguardando Pagamento Mesa'), ('Pago', 'Pago'), ('Aguardando Preparo', 'Aguardando Preparo'), ('Em preparo', 'Em preparo'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Com erro', 'Com erro'), ('Estornado', 'Estornado')], default='Sacola', max_length=25, verbose_name='Status do Pedido'),
        ),
    ]
