# Generated by Django 3.2.16 on 2023-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0180_alter_pedidos_status_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='taxa_de_atendimento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Taxa de atendimento '),
        ),
    ]
