# Generated by Django 3.2.16 on 2023-12-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0181_alter_pedidos_taxa_de_atendimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={'permissions': [('pode_ver_cozinha', 'Pode Ver Cozinha'), ('pode_ver_gestor_pedido', 'Pode Ver Gestor de Pedido')], 'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
    ]
