# Generated by Django 3.2.16 on 2023-12-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0182_alter_restaurante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pagamento_asaas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
