# Generated by Django 3.2.16 on 2024-11-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0184_alter_pedidos_taxa_de_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='slug',
            field=models.SlugField(help_text='Slug é um atalho para o nome do restaurante, sem espaços e caracteres especiais.', null=True, verbose_name='Slug do Restaurante'),
        ),
    ]
