# Generated by Django 3.2.16 on 2024-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0184_alter_pedidos_taxa_de_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacardapio',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
