# Generated by Django 3.2.16 on 2024-11-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0185_auto_20241126_1735'),
        ('pedidos', '0185_restaurante_slug'),
    ]

    operations = [
    ]
